<?php
return array (
  0 => 'config_id',
  1 => 'ma_muc_luc',
  2 => 'ma_phong',
  3 => 'hop_so',
  4 => 'ho_so_so',
  5 => 'tieu_de_ho_so',
  6 => 'ngay_thang',
  7 => 'ngay_bat_dau',
  8 => 'ngay_ket_thuc',
  9 => 'so_to',
  10 => 'thbq',
  11 => 'ghi_chu',
  12 => 'noi_dung_bai_bao',
  13 => 'aaaaassss',
  14 => 'noi_dung_bai_baofghgh',
  15 => 'dfsdfsdg',
  16 => 'tac_gia',
);